### ISSUE TITLE
Does not being loaded at all

### ISSUE THREAD

**Issue by weilbith** [mopidy/mopidy-youtube#102]
I've installed this module with and can verify it is available.
```sh
> sudo pip install Mopidy-Youtube
> pip show Mopidy-Youtube
Name: Mopidy-Youtube
Version: 2.0.2
Summary: Mopidy extension that plays sound from YouTube
Home-page: https://github.com/mopidy/mopidy-youtube
Author: Janez Troha
Author-email: dz0ny@ubuntu.si
License: Apache License, Version 2.0
Location: /usr/lib/python3.7/site-packages
Requires: requests, setuptools, Mopidy, pafy, Pykka
Required-by:
```

Just to be 100% sure I set in my `$XDG_CONFIG_HOME/mopidy/mopidy.conf`:
```toml
[youtube]
enabled = true
```

When I restart _Mopidy_ I get this log without mentioning this plugin to be loaded:
```
INFO     Starting Mopidy 2.2.2
INFO     Loading config from builtin defaults
INFO     Loading config from /home/thore/.config/mopidy/mopidy.conf
INFO     Loading config from command line options
INFO     Enabled extensions: mpd, http, stream, m3u, softwaremixer, file, local, local-sqlite
INFO     Disabled extensions: none
INFO     Starting Mopidy mixer: SoftwareMixer
INFO     Starting Mopidy audio
INFO     Starting Mopidy backends: StreamBackend, M3UBackend, FileBackend, LocalBackend
INFO     Audio output set to "autoaudiosink"
INFO     Loaded 1208 local tracks using sqlite
INFO     Starting Mopidy core
INFO     Starting Mopidy frontends: MpdFrontend, HttpFrontend
INFO     MPD server running at [::ffff:127.0.0.1]:6600
INFO     HTTP server running at [::ffff:127.0.0.1]:6680
INFO     Starting GLib mainloop
```

Also trying to play something as described in the `README` does not work:
```sh
> mpc add yt:https://youtu.be/_FrOQC-zEog
error adding yt:https://youtu.be/_FrOQC-zEog: directory or file not found
```

How can I get this working?

**Comment by kingosticks** [comment]
> Location: /usr/lib/**python3.7**/site-packages

It looks like there's some python2 vs python3 stuff going on here. Mopidy is currently still python2 only. If you run `mopidy deps` (https://docs.mopidy.com/en/latest/troubleshooting/) you'll see it displays all the extensions it can find. I guess you need to run `sudo pip2 install mopidy-youtube`.

**Comment by weilbith** [comment]
Ah, nice. Sry I forgot about it.

Now I get this error about missing `youtube-dl`
```
ERROR    Extension youtube failed during setup, this might have left the registry in a bad state.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mopidy/__main__.py", line 121, in main
    extension.setup(registry)
  File "/usr/lib/python2.7/site-packages/mopidy_youtube/__init__.py", line 29, in setup
    from .backend import YouTubeBackend
  File "/usr/lib/python2.7/site-packages/mopidy_youtube/backend.py", line 14, in <module>
    import pafy
  File "/usr/lib/python2.7/site-packages/pafy/__init__.py", line 7, in <module>
    from .pafy import new
  File "/usr/lib/python2.7/site-packages/pafy/pafy.py", line 52, in <module>
    "pafy: youtube-dl not found; you can use the internal backend by "
ImportError: pafy: youtube-dl not found; you can use the internal backend by setting the environmental variable PAFY_BACKEND to "internal". It is not enabled by default because it is not as well maintained as the youtube-dl backend.
```

But actually I have it available:
```sh
> youtube-dl -version
2019.02.18
```

How can I solve this? It proposes this `PAFY_BACKEND` internal stuff, but I guess that is not the actual solution for the problem.

**Comment by kingosticks** [comment]
I'd guess it's the same problem? python2 pafy will try to import python2 youtube-dl. `sudo pip2 install youtube-dl`?

**Comment by weilbith** [comment]
I hat this _Python_ 2 vs 3 sh**. Dependencies are not installed because they are satisfied, but actually they are not.

Never mind. After a problem with a too short video ID is solved (just don't use the YT share link) it works now.

What is not working anymore is my client `ncmpcpp` when I switch to my library explorer. _Mopidy_ is spamming this error and I can't close `ncmpcpp` via key internal binding anymore.
```
INFO     Searching YouTube for query '3OH!3'
ERROR    Unhandled exception in MpdSession (urn:uuid:eaa92eef-e61e-4d81-b158-6c2bfc7d4501):
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 201, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 304, in _handle_receive
    return self.on_receive(message)
  File "/usr/lib/python2.7/site-packages/mopidy/internal/network.py", line 423, in on_receive
    self.on_line_received(line)
  File "/usr/lib/python2.7/site-packages/mopidy/mpd/session.py", line 34, in on_line_received
    response = self.dispatcher.handle_request(line)
  File "/usr/lib/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 47, in handle_request
    return self._call_next_filter(request, response, filter_chain)
  File "/usr/lib/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 69, in _call_next_filter
    return next_filter(request, response, filter_chain)
  File "/usr/lib/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 77, in _catch_mpd_ack_errors_filter
    return self._call_next_filter(request, response, filter_chain)
  File "/usr/lib/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 69, in _call_next_filter
    return next_filter(request, response, filter_chain)
  File "/usr/lib/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 87, in _authenticate_filter
    return self._call_next_filter(request, response, filter_chain)
  File "/usr/lib/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 69, in _call_next_filter
    return next_filter(request, response, filter_chain)
  File "/usr/lib/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 106, in _command_list_filter
    response = self._call_next_filter(request, response, filter_chain)
  File "/usr/lib/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 69, in _call_next_filter
    return next_filter(request, response, filter_chain)
  File "/usr/lib/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 135, in _idle_filter
    response = self._call_next_filter(request, response, filter_chain)
  File "/usr/lib/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 69, in _call_next_filter
    return next_filter(request, response, filter_chain)
  File "/usr/lib/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 148, in _add_ok_filter
    response = self._call_next_filter(request, response, filter_chain)
  File "/usr/lib/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 69, in _call_next_filter
    return next_filter(request, response, filter_chain)
  File "/usr/lib/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 160, in _call_handler_filter
    response = self._format_response(self._call_handler(request))
  File "/usr/lib/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 175, in _call_handler
    return protocol.commands.call(tokens, context=self.context)
  File "/usr/lib/python2.7/site-packages/mopidy/mpd/protocol/__init__.py", line 180, in call
    return self.handlers[tokens[0]](context, *tokens[1:])
  File "/usr/lib/python2.7/site-packages/mopidy/mpd/protocol/__init__.py", line 142, in validate
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/mopidy/mpd/protocol/music_db.py", line 145, in find
    results = context.core.library.search(query=query, exact=True).get()
  File "/usr/lib/python2.7/site-packages/pykka/threading.py", line 52, in get
    compat.reraise(*self._data['exc_info'])
  File "/usr/lib/python2.7/site-packages/pykka/compat.py", line 12, in reraise
    exec('raise tp, value, tb')
  File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 201, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 295, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/usr/lib/python2.7/site-packages/mopidy/core/library.py", line 348, in search
    result = future.get()
  File "/usr/lib/python2.7/site-packages/pykka/threading.py", line 52, in get
    compat.reraise(*self._data['exc_info'])
  File "/usr/lib/python2.7/site-packages/pykka/compat.py", line 12, in reraise
    exec('raise tp, value, tb')
  File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 201, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 295, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/usr/lib/python2.7/site-packages/mopidy_youtube/backend.py", line 192, in search
    tracks=search_youtube(search_query)
  File "/usr/lib/python2.7/site-packages/mopidy_youtube/backend.py", line 102, in search_youtube
    playlist = [item['id']['videoId'] for item in data['items']]
KeyError: u'items'
```

How can I solve this?

**Comment by kingosticks** [comment]
That is https://github.com/mopidy/mopidy-youtube/issues/87
